import type { ProductType } from "@/types/quote-builder"

// TRUDOOR product configuration data
export const PRODUCT_TYPES: ProductType[] = [
  {
    id: "metal-door",
    name: "Metal Door",
    description: "Interior or Exterior Use",
    image: "/placeholder.svg?height=200&width=200",
    sections: [
      {
        id: 1,
        title: "Select Metal Door Type",
        type: "single",
        required: true,
        columns: 2,
        options: [
          {
            id: 1,
            label: "Door with Frame",
            value: "door-with-frame",
            description: "18 gauge door w/ 16 gauge frame - primed gray",
            image: "/placeholder.svg?height=150&width=150",
          },
          {
            id: 2,
            label: "Replacement Door Only",
            value: "replacement-only",
            description: "18 gauge primed gray door - re-use existing frame",
            image: "/placeholder.svg?height=150&width=150",
          },
        ],
      },
      {
        id: 2,
        title: "Single or Double Door",
        type: "single",
        required: true,
        columns: 2,
        options: [
          {
            id: 46,
            label: "Single Door",
            value: "single",
            image: "/placeholder.svg?height=200&width=150",
          },
          {
            id: 47,
            label: "Double Door",
            value: "double",
            image: "/placeholder.svg?height=200&width=200",
          },
        ],
      },
      {
        id: 3,
        title: "Door Width",
        type: "single",
        required: true,
        columns: 4,
        tooltip: "Select the door width that matches your opening requirements",
        options: [
          { id: 3, label: "2'0\" (24 inch)", value: "24", description: '23-3/4" Actual Size' },
          { id: 4, label: "2'4\" (28 inch)", value: "28", description: '27-3/4" Actual Size' },
          { id: 5, label: "2'6\" (30 inch)", value: "30", description: '29-3/4" Actual Size', isPopular: true },
          { id: 6, label: "2'8\" (32 inch)", value: "32", description: '31-3/4" Actual Size' },
          { id: 7, label: "2'10\" (34 inch)", value: "34", description: '33-3/4" Actual Size' },
          { id: 8, label: "3'0\" (36 inch)", value: "36", description: '35-3/4" Actual Size' },
          { id: 9, label: "3'4\" (40 inch)", value: "40", description: '39-3/4" Actual Size' },
          { id: 10, label: "3'6\" (42 inch)", value: "42", description: '41-3/4" Actual size' },
          { id: 11, label: "3'8\" (44 inch)", value: "44", description: '43-3/4" Actual Size' },
          { id: 12, label: "4'0\" (48 inch)", value: "48", description: '47-3/4" Actual Size' },
        ],
        optionConditions: [
          {
            params: [{ section: 2, options: [46], condition: "IN" }],
            show: [3, 4, 5, 6, 7, 8, 9, 10],
          },
          {
            params: [{ section: 2, options: [47], condition: "IN" }],
            show: [9, 10, 11, 12],
          },
        ],
      },
      {
        id: 4,
        title: "Door Height",
        type: "single",
        required: true,
        columns: 2,
        options: [
          { id: 13, label: "6'8\" (80 inch)", value: "80" },
          { id: 14, label: "7'0\" (84 inch)", value: "84" },
          { id: 15, label: "8'0\" (96 inch)", value: "96" },
          { id: 16, label: "Other", value: "other", customInput: true },
        ],
        customInputLabel: "Enter custom height (inches):",
      },
      {
        id: 5,
        title: "What is the Door Hand?",
        type: "single",
        required: true,
        columns: 2,
        tooltip: "Door hand determines which side the hinges are on and which way the door swings",
        sectionConditions: [[{ section: 2, options: [46], condition: "IN" }]],
        options: [
          { id: 48, label: "LH (Left Hand)", value: "lh", description: "Hinges on left, opens away from you" },
          { id: 49, label: "RH (Right Hand)", value: "rh", description: "Hinges on right, opens away from you" },
          { id: 50, label: "LHR (Left Hand Reverse)", value: "lhr", description: "Hinges on left, opens toward you" },
          { id: 51, label: "RHR (Right Hand Reverse)", value: "rhr", description: "Hinges on right, opens toward you" },
        ],
      },
      {
        id: 6,
        title: "Which Door is Active?",
        type: "single",
        required: true,
        columns: 2,
        sectionConditions: [[{ section: 2, options: [47], condition: "IN" }]],
        options: [
          { id: 52, label: "LHRA (Left Hand Reverse Active)", value: "lhra" },
          { id: 53, label: "LHA (Left Hand Active)", value: "lha" },
          { id: 54, label: "RHA (Right Hand Active)", value: "rha" },
          { id: 55, label: "RHRA (Right Hand Reverse Active)", value: "rhra" },
          { id: 56, label: "Both Active (Push/Pull)", value: "both-push-pull" },
          { id: 57, label: "Both Active (Pull/Push)", value: "both-pull-push" },
          { id: 58, label: "Both Active (Push/Push)", value: "both-push-push" },
        ],
      },
      {
        id: 7,
        title: "Interior or Exterior Application",
        type: "single",
        required: true,
        columns: 2,
        options: [
          { id: 83, label: "Interior", value: "interior", description: "For indoor use only" },
          { id: 84, label: "Exterior", value: "exterior", description: "Weather-resistant for outdoor use" },
        ],
      },
      {
        id: 8,
        title: "Does this door need to be Fire-Rated?",
        type: "single",
        required: true,
        columns: 3,
        tooltip: "Fire ratings are required by building codes in certain applications",
        sectionConditions: [
          [
            { section: 7, options: [83], condition: "IN" },
            { section: 6, options: [56, 57], condition: "NOT" },
          ],
        ],
        options: [
          { id: 59, label: "No", value: "no" },
          { id: 60, label: "20 Minute", value: "20min" },
          { id: 61, label: "45 Minute", value: "45min" },
          { id: 62, label: "60 Minute", value: "60min" },
          { id: 63, label: "90 Minute", value: "90min" },
          { id: 64, label: "3 Hour", value: "3hour", warning: "Requires special wall construction" },
        ],
      },
      {
        id: 14,
        title: "Add Door Frame",
        type: "single",
        required: true,
        columns: 2,
        sectionConditions: [[{ section: 1, options: [1], condition: "IN" }]],
        options: [
          { id: 93, label: "Wood Stud", value: "wood-stud", description: "Standard wood frame construction" },
          { id: 94, label: "Steel Stud", value: "steel-stud", description: "Metal stud frame construction" },
          { id: 95, label: "New Block", value: "new-block", description: "New masonry block wall" },
          { id: 96, label: "Existing Block", value: "existing-block", description: "Retrofit into existing masonry" },
        ],
      },
      {
        id: 15,
        title: "Has the wall been built yet?",
        type: "single",
        required: true,
        columns: 2,
        sectionConditions: [
          [
            { section: 14, options: [93, 94], condition: "IN" },
            { section: 8, options: [64], condition: "NOT" },
          ],
        ],
        options: [
          {
            id: 97,
            label: "Yes",
            value: "wall-built",
            description: "Wall is already constructed - frame will be installed into existing opening",
          },
          {
            id: 98,
            label: "No",
            value: "wall-not-built",
            description: "Wall will be built around the frame - more flexibility in sizing",
          },
        ],
      },
      {
        id: 16,
        title: "Wall Thickness",
        type: "single",
        required: true,
        columns: 2,
        sectionConditions: [[{ section: 14, options: [93, 94, 95, 96], condition: "IN" }]],
        options: [
          { id: 99, label: '4" Wall', value: "4inch" },
          { id: 100, label: '6" Wall', value: "6inch" },
          { id: 101, label: '8" Wall', value: "8inch" },
          { id: 102, label: "Other", value: "other", customInput: true },
        ],
        customInputLabel: "Enter wall thickness (inches):",
      },
    ],
  },
  {
    id: "wood-door",
    name: "Wood Door",
    description: "Interior Use Only",
    image: "/placeholder.svg?height=200&width=200",
    sections: [
      {
        id: 1,
        title: "Single or Double Door",
        type: "single",
        required: true,
        columns: 2,
        options: [
          {
            id: 46,
            label: "Single Door",
            value: "single",
            image: "/placeholder.svg?height=200&width=150",
          },
          {
            id: 47,
            label: "Double Door",
            value: "double",
            image: "/placeholder.svg?height=200&width=200",
          },
        ],
      },
      {
        id: 2,
        title: "Wood Type",
        type: "single",
        required: true,
        columns: 2,
        options: [
          { id: 80, label: "Oak", value: "oak", description: "Durable hardwood with prominent grain" },
          { id: 81, label: "Maple", value: "maple", description: "Light colored hardwood" },
          { id: 82, label: "Cherry", value: "cherry", description: "Rich reddish hardwood" },
          { id: 83, label: "Pine", value: "pine", description: "Affordable softwood option" },
        ],
      },
    ],
  },
  {
    id: "metal-building-door",
    name: "Metal Building Door",
    description: "Pre-Engineered Steel Building Use",
    image: "/placeholder.svg?height=200&width=200",
    sections: [
      {
        id: 1,
        title: "System Size",
        type: "single",
        required: true,
        columns: 2,
        options: [
          { id: 1, label: "Standard Size", value: "standard", description: "Pre-engineered standard dimensions" },
          {
            id: 2,
            label: "Custom Size",
            value: "custom",
            customInput: true,
            description: "Custom dimensions for your building",
          },
        ],
        customInputLabel: "Enter custom dimensions (W x H):",
      },
    ],
  },
  {
    id: "metal-frame-only",
    name: "Metal Frame Only",
    description: "Frame Only - No Door",
    image: "/placeholder.svg?height=200&width=200",
    sections: [
      {
        id: 1,
        title: "Frame Type",
        type: "single",
        required: true,
        columns: 2,
        options: [
          { id: 1, label: "Standard Frame", value: "standard", description: "16 gauge steel frame" },
          { id: 2, label: "Fire-Rated Frame", value: "fire-rated", description: "Fire-rated steel frame" },
        ],
      },
    ],
  },
  {
    id: "lite-kits-glazing",
    name: "Lite Kits & Glazing",
    description: "Glass and glazing components",
    image: "/placeholder.svg?height=200&width=200",
    isHardwareOnly: true,
    sections: [],
  },
  {
    id: "door-hardware",
    name: "Door Hardware",
    description: "Handles, locks, and hardware",
    image: "/placeholder.svg?height=200&width=200",
    isHardwareOnly: true,
    sections: [],
  },
  {
    id: "louvers",
    name: "Louvers",
    description: "Ventilation louvers",
    image: "/placeholder.svg?height=200&width=200",
    isHardwareOnly: true,
    sections: [],
  },
]
